version: "2"
services:
  fabric8-gemini-server:
    build:
      context: .
    network_mode: bridge
    entrypoint:
      - /bin/entrypoint.sh
    environment:
      POSTGRESQL_USER: coreapi
      POSTGRESQL_PASSWORD: coreapipostgres
      POSTGRESQL_DATABASE: coreapi
      PGBOUNCER_SERVICE_HOST: bayesian-pgbouncer
      PGBOUNCER_SERVICE_PORT: "5432"
      GEMINI_API_SERVICE_TIMEOUT: "60"
      GEMINI_API_SERVICE_PORT: "5000"
      NUMBER_WORKER_PROCESS: "2"
      CLASS_TYPE: "sync"
      SENTRY_DSN: ""
    ports:
      - "5000:5000"
